/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddFeature1669706986248 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      create table feature (
        id smallint generated by default as identity,
        name character varying not null,
        code character varying not null,
        is_enabled boolean not null,
        primary key (id)
      );
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
