/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class RefactorScheduler1692885285551 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      drop sequence schedule_id_seq;
      alter table schedule
        alter column id set not null,
        alter column id add generated by default as identity;

      drop sequence schedule_event_id_seq;
      alter table schedule_event
        alter column id set not null,
        alter column id add generated by default as identity;
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
