/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class DemoData1696500815450 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      create table demo_data (
        id integer generated by default as identity,
        account_id integer not null,
        type character varying not null,
        ids character varying not null,
        primary key (id),
        foreign key (account_id) references account(id) on delete cascade
      );   
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
