/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class TutorialItem1710929893275 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      create table tutorial_item (
        id integer generated by default as identity,
        account_id integer not null,
        group_id integer not null,
        created_at timestamp without time zone not null,
        name character varying not null,
        link character varying not null,
        sort_order integer not null,
        primary key (id),
        foreign key (account_id) references account(id) on delete cascade,
        foreign key (group_id) references tutorial_group(id) on delete cascade
      );
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
