/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AutomationProcess1718724129043 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      create table automation_process (
        id integer generated by default as identity,
        account_id integer not null,
        created_at timestamp without time zone not null default now(),
        type text not null default 'simple',
        is_active boolean not null default false,
        external_id text,
        data text,
        primary key (id),
        foreign key (account_id) references account(id) on delete cascade
      );
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
