/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AppSumoLicense1720194016236 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      create table app_sumo_license (
        id integer generated by default as identity,
        license_key text not null,
        license_status text not null,
        plan_id text not null,
        tier integer not null,
        account_id integer,
        created_at timestamp without time zone not null default now(),
        primary key (id),
        foreign key (account_id) references account(id) on delete set null
      );
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
