/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AppSumoPreset1720194705296 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      create table app_sumo_preset (
        id integer generated by default as identity,
        tier integer not null,
        user_count integer not null,
        term_in_days integer not null,
        primary key (id)
      );
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
