/* eslint-disable max-len */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class UserIdIdentity1724944661564 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
      DROP SEQUENCE IF EXISTS user_id_seq;
      DO $$ 
      DECLARE
          max_id integer;
      BEGIN
          SELECT COALESCE(MAX(id), 0) + 1 INTO max_id FROM users;
          EXECUTE 'ALTER TABLE users ALTER COLUMN id SET NOT NULL, ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH ' || max_id || ')';
      END $$;
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
