/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddVersion1731682593963 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      create table version (
          id integer generated by default as identity,
          version varchar(255) not null,
          date timestamp without time zone not null,
          primary key ("id"),
          unique ("version")
      );
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
