/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-empty-function */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddSubscriptionDiscount1737039160966 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      create table subscription_discount (
        id integer generated by default as identity,
        days integer not null,
        percent integer not null,
        code text,
        primary key (id)
      );
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {}
}
