const DefaultUIFields = ['OwnerId', 'Name', 'Description'];

export const SalesforceUIFields = new Map([
  ['Account', [...DefaultUIFields, 'Phone', 'Website', 'Industry', 'Type']],
  ['Activity', [...DefaultUIFields, 'Subject', 'Status', 'ActivityDate', 'StartDateTime', 'EndDateTime']],
  ['Approval', DefaultUIFields],
  ['Attachment', DefaultUIFields],
  ['CampaignMember', DefaultUIFields],
  ['Campaigns', DefaultUIFields],
  ['Case', DefaultUIFields],
  ['Contact', [...DefaultUIFields, 'Email', 'Phone', 'Title']],
  ['Contract', DefaultUIFields],
  ['Dashboard', DefaultUIFields],
  ['DashboardComponent', DefaultUIFields],
  ['EmailTemplate', DefaultUIFields],
  ['Event', DefaultUIFields],
  ['Folder', DefaultUIFields],
  ['Group', DefaultUIFields],
  ['PageLayout', DefaultUIFields],
  ['Lead', [...DefaultUIFields, 'Email', 'Phone', 'Company', 'Title', 'Status', 'Rating']],
  ['ListView', DefaultUIFields],
  ['Opportunity', [...DefaultUIFields, 'StageName', 'Amount', 'Probability', 'Type', 'ForecastCategory', 'CloseDate']],
  ['OpportunityLineItem', DefaultUIFields],
  ['Order', DefaultUIFields],
  ['OrderItem', DefaultUIFields],
  ['Pricebook', DefaultUIFields],
  ['Pricebook2', DefaultUIFields],
  ['Product', DefaultUIFields],
  ['Product2', DefaultUIFields],
  ['Profile', DefaultUIFields],
  ['Report', DefaultUIFields],
  ['SharingRule', DefaultUIFields],
  ['Task', [...DefaultUIFields, 'Subject', 'Status', 'Priority', 'DueDate', 'IsClosed']],
  ['User', [...DefaultUIFields, 'Email', 'Phone', 'Company', 'Title', 'Username', 'IsActive']],
  ['UserRole', DefaultUIFields],
]);
