### Get entity type

GET {{url}}/api/crm/entity-types/{{entityTypeId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Get entity types
GET {{url}}/api/crm/entity-types
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete entity type

DELETE {{url}}/api/crm/entity-types/321
Content-Type: application/json
Authorization: Bearer {{token}}

### Update entity type

PUT {{url}}/api/crm/entity-types/{{entityTypeId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": {{entityTypeId}},
  "name": "Deal",
  "cardView": "fields_and_notes",
  "fieldGroups": [
    {
      "id": {{fieldGroupId}},
      "name": "Details",
      "sortOrder": 0,
      "state": "created"
    }
  ],
  "fields": [
    {
      "id": 4201,
      "name": "Field name",
      "type": "text",
      "sortOrder": 1,
      "fieldGroupId": {{fieldGroupId}},
      "state": "updated"
    },
    {
      "id": 4202,
      "name": "Field name",
      "type": "select",
      "sortOrder": 1,
      "fieldGroupId": {{fieldGroupId}},
      "options": [
        {
          "id": 1,
          "label": "Option 1",
          "sortOrder": 0,
          "state": "created"
        },
        {
          "id": 2,
          "label": "Option 2",
          "sortOrder": 1,
          "state": "created"
        }
      ],
      "state": "created"
    }
  ],
  "featureIds": [1, 2, 3],
  "taskSettingsActiveFields": ["planned_time", "board_name", "start_date", "end_date", "description", "subtasks"],
  "linkedEntityTypes": [],
  "section": {
    "name": "Deals",
    "view": "board",
    "icon": "crown"
  }
}
